#
# written by Markus F. X. J. Oberhumer <markus@oberhumer.com>
#
# to use a specific python version call
#   `make PYTHON=python2.2'
#

SHELL = /bin/sh

PYTHON = python2.2
PYTHON = python

default:

test:
	$(PYTHON) playmus.py *.mp3 *.mod

.PHONY: default test

